# Name of the GitHub Action
name: Generate Snake Contribution Graph

# Controls when the action will run. This action runs every 6 hours and can be manually triggered.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI.

# The jobs that will run as part of this workflow
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Sequence of tasks to execute
    steps:
    # Checkout the current repository to access its content
    - name: Checkout repository
      uses: actions/checkout@v2

    # Generate the snake GIF and SVG
    - name: Generate snake from contributions
      uses: Platane/snk@master
      with:
        github_user_name: razo-11996
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

    # Display the changes made to the repo during the workflow
    - name: Display changes
      run: git diff
